name: Create docker image

on: [ push ]

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
            timezone: Europe/Bratislava  
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: scholtz2
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./CovidMassTesting/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            scholtz2/mass-covid-testing-api:latest
